# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e517f0da-e89b-4c38-8414-c01df0c4469b";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e517f0da-e89b-4c38-8414-c01df0c4469b";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime"];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/e517f0da-e89b-4c38-8414-c01df0c4469b";
      fsType = "btrfs";
      options = [ "subvol=@persist" "compress=zstd" "noatime"];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/e517f0da-e89b-4c38-8414-c01df0c4469b";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime"];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/e517f0da-e89b-4c38-8414-c01df0c4469b";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/748A-8625";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  swapDevices = [
    {
      device = "/swap/swapfile";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
