# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7e21a086-914f-4f5e-b389-e4e02d5cd973";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/7e21a086-914f-4f5e-b389-e4e02d5cd973";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/7e21a086-914f-4f5e-b389-e4e02d5cd973";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/7e21a086-914f-4f5e-b389-e4e02d5cd973";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/7e21a086-914f-4f5e-b389-e4e02d5cd973";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/923F-2A2B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
